name: Linux
env:
  VK_VERSION: 1.3.204.1
on:
  push:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        shell: bash
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y make gcc g++ mesa-common-dev libglu1-mesa-dev libxxf86dga-dev libxxf86vm-dev libasound2-dev libx11-dev libxcb1-dev
      - name: Download and Install Vulkan SDK
        shell: bash
        run: |
          curl -L -v -o vulkansdk-linux-x86_64-$VK_VERSION.tar.gz -O https://sdk.lunarg.com/sdk/download/$VK_VERSION/linux/vulkan_sdk.tar.gz?Human=true
          tar zxf vulkansdk-linux-x86_64-$VK_VERSION.tar.gz
      - name: Build vkQuake2 Debug
        shell: bash
        run: |
          export VULKAN_SDK=$GITHUB_WORKSPACE/$VK_VERSION/x86_64
          cd linux
          make clean debug
          cd ..
      - name: Upload vkQuake2 Debug artifacts
        uses: actions/upload-artifact@v2.1.3
        with:
          name: vkQuake2-Ubuntu-debug-x64
          path: |
            linux/debugx64
            !linux/debugx64/**/*.o
      - name: Build vkQuake2 Release
        shell: bash
        run: |
          export VULKAN_SDK=$GITHUB_WORKSPACE/$VK_VERSION/x86_64
          cd linux
          make clean release
          cd ..
      - name: Upload vkQuake2 Release artifacts
        uses: actions/upload-artifact@v2.1.3
        with:
          name: vkQuake2-Ubuntu-release-x64
          path: |
            linux/releasex64
            !linux/releasex64/**/*.o
